export const data = [
  {
    nome: "Limpeza Residencial",
    descricao: "Serviço completo de limpeza para sua residência.",
    email: "contato@limpezaresidencial.com",
    telefone: "(11) 98765-4321",
    imagem: 0,
    categoria: ["Limpeza", "Casa"],
  },
  {
    nome: "Jardinagem",
    descricao: "Cuidado e manutenção de jardins.",
    email: "contato@jardinagemverde.com",
    telefone: "(11) 91234-5678",
    imagem: 1,
    categoria: ["Limpeza"],
  },
  {
    nome: "Reformas",
    descricao: "Serviços gerais de reformas para sua casa ou empresa.",
    email: "contato@reformasgerais.com",
    telefone: "(11) 99876-5432",
    imagem: 2,
    categoria: ["Casa"],
  },
  {
    nome: "Transporte Escolar",
    descricao: "Transporte seguro para crianças e adolescentes.",
    email: "contato@transporteescolar.com",
    telefone: "(11) 93456-7890",
    imagem: 3,
    categoria: ["Transporte"],
  },
  {
    nome: "Serviço de Buffet",
    descricao: "Buffet completo para eventos e festas.",
    email: "contato@buffetfestas.com",
    telefone: "(11) 92345-6789",
    imagem: 4,
    categoria: ["Alimentos"],
  },
  {
    nome: "Consultoria Financeira",
    descricao: "Auxílio para organizar suas finanças pessoais e empresariais.",
    email: "contato@consultoriafinanceira.com",
    telefone: "(11) 98765-1234",
    imagem: 5,
    categoria: ["Consultoria"],
  },
  {
    nome: "Aulas Particulares",
    descricao: "Aulas particulares para diversos níveis de ensino.",
    email: "contato@aulaparticular.com",
    telefone: "(11) 91234-8765",
    imagem: 6,
    categoria: ["Consultoria"],
  },
  {
    nome: "Serviço de Entregas",
    descricao: "Entregas rápidas e seguras.",
    email: "contato@entregasrapidas.com",
    telefone: "(11) 97654-3210",
    imagem: 7,
    categoria: ["Transporte", "Comodidade"],
  },
  {
    nome: "Assistência Técnica",
    descricao: "Suporte técnico para eletrônicos e eletrodomésticos.",
    email: "contato@assistenciatecnica.com",
    telefone: "(11) 92345-0987",
    imagem: 8,
    categoria: ["Eletrônicos"],
  },
  {
    nome: "Pet Care",
    descricao: "Cuidado e bem-estar para o seu pet.",
    email: "contato@petcare.com",
    telefone: "(11) 93456-1234",
    imagem: 9,
    categoria: ["Saúde"],
  },
  {
    nome: "Design Gráfico",
    descricao: "Criação de materiais visuais e gráficos.",
    email: "contato@designgrafico.com",
    telefone: "(11) 94321-8765",
    imagem: 10,
    categoria: ["Consultoria"],
  },
  {
    nome: "Consultoria de Marketing",
    descricao: "Planejamento e execução de estratégias de marketing.",
    email: "contato@marketingconsultoria.com",
    telefone: "(11) 98712-3456",
    imagem: 11,
    categoria: ["Consultoria"],
  },
  {
    nome: "Desenvolvimento Web",
    descricao: "Criação de sites e aplicativos web.",
    email: "contato@desenvolvimentoweb.com",
    telefone: "(11) 95678-1234",
    imagem: 12,
    categoria: ["Informática"],
  },
  {
    nome: "Fotografia Profissional",
    descricao: "Serviço de fotografia para eventos e empresas.",
    email: "contato@fotografiaprofissional.com",
    telefone: "(11) 93421-0987",
    imagem: 13,
    categoria: ["Fotos"],
  },
  {
    nome: "Consultoria Jurídica",
    descricao: "Apoio jurídico especializado.",
    email: "contato@consultoriajuridica.com",
    telefone: "(11) 94321-5678",
    imagem: 14,
    categoria: ["Consultoria"],
  },
  {
    nome: "Academia Personal",
    descricao: "Aulas personalizadas de fitness.",
    email: "contato@academiapersonal.com",
    telefone: "(11) 98765-4320",
    imagem: 15,
    categoria: ["Saúde"],
  },
  {
    nome: "Tradução e Interpretação",
    descricao: "Serviços de tradução e interpretação de idiomas.",
    email: "contato@traducaoeinterpretacao.com",
    telefone: "(11) 93214-8765",
    imagem: 16,
    categoria: ["Consultoria"],
  },
  {
    nome: "Manutenção de Computadores",
    descricao: "Conserto e manutenção de computadores e notebooks.",
    email: "contato@manutencaopc.com",
    telefone: "(11) 94567-8901",
    imagem: 17,
    categoria: ["Informática"],
  },
  {
    nome: "Lavagem de Carros",
    descricao: "Lavagem e polimento automotivo.",
    email: "contato@lavagemcarros.com",
    telefone: "(11) 93456-7890",
    imagem: 18,
    categoria: ["Limpeza", "Carros"],
  },
  {
    nome: "Produção de Vídeos",
    descricao: "Produção de vídeos institucionais e publicitários.",
    email: "contato@producaodevideos.com",
    telefone: "(11) 97654-3211",
    imagem: 19,
    categoria: ["Informática", "Fotos"],
  },
];

export const categorias = [
  "Limpeza",
  "Casa",
  "Transporte",
  "Alimentos",
  "Consultoria",
  "Comodidade",
  "Eletrônicos",
  "Saúde",
  "Fotos",
  "Informática",
  "Carros",
];
